package com.ids.entity;

import java.time.Instant;
import java.time.LocalDate;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.relational.core.mapping.Column;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

//CREATE TABLE facture (
//		  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
//		  "date_creation" timestamp,
//		  "date_facturation" date,
//		  PRIMARY KEY ("id")
//)

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
@EqualsAndHashCode(of = "id")
public class Facture {

	@Id
	private Long id;
	@CreatedDate
	private Instant dateCreation;
	@LastModifiedDate
	@Column("derniere_maj")
	private Instant dateMaj;
	private LocalDate dateFacturation;
//	private Client client;
//	private List<LigneFacture> lignes;

}
